export = BigInteger;
declare function BigInteger(n: any, s: any, token: any): BigInteger;
declare class BigInteger {
    constructor(n: any, s: any, token: any);
    _d: any;
    _s: any;
    toString(base: any): string;
    add(n: any): any;
    negate(): BigInteger;
    abs(): BigInteger;
    subtract(n: any): any;
    compareAbs(n: any): any;
    compare(n: any): any;
    isUnit(): boolean;
    multiply(n: any): any;
    multiplySingleDigit(n: any): any;
    square(): BigInteger;
    quotient(n: any): any;
    divide: any;
    remainder(n: any): any;
    divRem(n: any): {};
    divRemSmall(n: any): {};
    isEven(): boolean;
    isOdd(): boolean;
    sign(): any;
    isPositive(): boolean;
    isNegative(): boolean;
    isZero(): boolean;
    exp10(n: any): any;
    pow(n: any): BigInteger;
    modPow(exponent: any, modulus: any): BigInteger;
    log(): any;
    valueOf(): any;
    toJSValue(): any;
    lowVal(): any;
}
declare namespace BigInteger {
    export { CONSTRUCT };
    export function _construct(n: any, s: any): BigInteger;
    export { BigInteger_base as base };
    export { BigInteger_base_log10 as base_log10 };
    export { ZERO };
    export { ONE };
    export { M_ONE };
    export { ZERO as _0 };
    export { ONE as _1 };
    export const small: {};
    export const digits: any;
    export const radixRegex: {};
    export function parse(s: any, base: any): BigInteger;
    export { MAX_EXP };
}
declare var CONSTRUCT: {};
declare var BigInteger_base: number;
declare var BigInteger_base_log10: number;
declare var ZERO: BigInteger;
declare var ONE: BigInteger;
declare var M_ONE: BigInteger;
declare var MAX_EXP: BigInteger;
